netlify.toml

chore: Add npm ci

---

.github/release-please/.config.json
.github/workflows/release-bins.yml
.github/workflows/release-docker.yml
.github/workflows/release-docs.yml
.github/workflows/release-please.yml
.github/workflows/scorecard.yml
.typos.toml
CONTRIBUTING.md
Cargo.lock
README.md
docs/antora.yml
docs/package-lock.json
docs/package.json

- Fix docs pipeline
- Adjust permission for attestations
- Remove hardcoded links for docs

fix: Docs pipeline

---

.github/workflows/scorecard.yml
Cargo.lock

- Removes the create-github-app-token action from the scorecard workflow

fix: remove the create-github-app-token action from the scorecard workflow

---

.github/workflows/cla.yml
.pre-commit-config.yaml
.yamlfix.toml
Cargo.lock

Fixes CLA assistant and labels
https://linear.app/openzeppelin-development/issue/PLAT-6534/fix-cla-assistant-and-label-bug

fix: CLA labels and assistant

---

.github/workflows/rc.yml
.github/workflows/release-bins.yml
.github/workflows/release-docker.yml
.github/workflows/release-docs.yml
.github/workflows/release-please.yml
.github/workflows/release-sbom.yml
Cargo.lock

Updates the docs branch and actions/create-github-app-toke version

chore: update docs branch and actions/create-github-app-toke version

---

.github/pull_request_template.md
Cargo.lock

- Updates PR template with more checklist items

chore: Update PR template

---

src/models/blockchain/mod.rs
src/models/config/monitor_config.rs
src/models/core/monitor.rs
src/models/core/network.rs
src/models/core/trigger.rs
src/models/security/secret.rs

https://linear.app/openzeppelin-development/issue/PLAT-6627/improving-validation-for-parsing-configs
- Adding validation when we parse the config files. Doing this, we get the user clear information about errors inside the config files regarding the expected field names.
Example:

fix: Adding validation for unknown field names

---

.github/release-please/.config.json
.github/workflows/release-bins.yml
.github/workflows/release-docs.yml
.github/workflows/release-please.yml
.github/workflows/release-sbom.yml
.github/workflows/rust-docs-url.yml
docs/antora.yml
docs/modules/ROOT/nav.adoc

chore: Fix release bugs

---

docs/modules/ROOT/nav.adoc

- Fix tech rust docs references

chore: Fix tech rust docs ref

---

.github/actions/prepare/action.yml
.github/workflows/release-please.yml
.github/workflows/rust-docs-url.yml
Cargo.lock
rust-toolchain.toml
src/models/blockchain/mod.rs
src/utils/logging/mod.rs
tests/integration/bootstrap/main.rs
tests/integration/filters/stellar/filter.rs
tests/integration/mocks/models.rs

chore: Minor fixes to ci releases

---

.github/workflows/ci.yaml
docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/pages/rpc.adoc

- Update index and rpc docs to reflect the updates
- Ignore running ci on docs and `*.md` files.

docs: Update index and rpc docs

---

examples/config/networks/ethereum_sepolia.json

Fixed the chain id for Sepolia example network config.

chore: Update chain id for Sepolia example

---

README.md

chore: add the scorecard badge

---

examples/config/networks/base.json
examples/config/networks/base_sepolia.json
examples/config/networks/bsc_mainnet.json
examples/config/networks/bsc_testnet.json
scripts/validate_network_config.sh

Fixed validator script. 
Added some more sample network configs

chore: Fixed validator script. Added sample network configs

---

.github/actions/prepare/action.yml
.github/workflows/ci.yaml
.github/workflows/release-docker.yml
.gitignore
Cargo.lock
DOCKER_README.md
Dockerfile.development
Dockerfile.production
README.md
docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/pages/quickstart.adoc

docs: Add overview to dockerhub

---

.github/workflows/release-docker.yml
Cargo.toml
docs/modules/ROOT/pages/index.adoc
src/services/blockchain/transports/endpoint_manager.rs
src/services/filter/filters/evm/evaluator.rs
src/services/filter/filters/stellar/evaluator.rs
src/services/notification/mod.rs
src/services/notification/telegram.rs
src/utils/monitor/execution.rs
tests/integration/bootstrap/main.rs

fix: Bump MSRV

---

DOCKER_README.md

- Fix docker readme emoji with actual unicode character

fix: Use unicode character for emoji

---

README.md
docs/modules/ROOT/pages/index.adoc

- Updating README file
- Delete message about alpha stage

chore: Update readme file

---

.github/workflows/release-bins.yml
.github/workflows/test-bins.yml

- Fixes binaries release and enable new nightly workflow to test binaries compilation

fix: Release binaries and enable nightly workflows to create binary artifacts and images

---

.github/workflows/semgrep.yml

[PS-13](https://linear.app/openzeppelin-development/issue/PS-13/semgrep-cicd-integration)
Fix env var error value in `semgrep.yml`

fix: correct env var value in semgrep.yml

---

.github/workflows/codeql.yml

([PS-25](https://linear.app/openzeppelin-development/issue/PS-25/improve-security-scorecard))
CodeQL code scanning support for Rust is public review now. This will hopefully fix the current configuration error for CodeQL of this repo.

chore: Add codeql.yml
